// Complete list of Rick Beato's "What Makes This Song Great" episodes
const songsData = [
  { episode: 1, artist: "Blink-182", song: "All the Small Things" },
  { episode: 2, artist: "The Police", song: "Every Little Thing She Does Is Magic" },
  { episode: 3, artist: "Steely Dan", song: "Kid Charlemagne" },
  { episode: 4, artist: "Nirvana", song: "On A Plain" },
  { episode: 5, artist: "Pearl Jam", song: "Jeremy" },
  { episode: 6, artist: "Linkin Park", song: "Numb" },
  { episode: 7, artist: "Tom Petty", song: "I Won't Back Down" },
  { episode: 8, artist: "A Perfect Circle", song: "Judith" },
  { episode: 9, artist: "Toto", song: "Rosanna" },
  { episode: 10, artist: "Soundgarden", song: "Superunknown" },
  { episode: 11, artist: "Metallica", song: "Enter Sandman" },
  { episode: 12, artist: "Alice In Chains", song: "Them Bones" },
  { episode: 13, artist: "Tool", song: "Schism" },
  { episode: 14, artist: "Foo Fighters", song: "Everlong" },
  { episode: 15, artist: "Tool", song: "Schism" },
  { episode: 16, artist: "Foo Fighters", song: "Everlong" },
  { episode: 17, artist: "Boston", song: "Hitch a Ride" },
  { episode: 18, artist: "Ariana Grande", song: "Into You" },
  { episode: 19, artist: "Rush", song: "Closer to the Heart" },
  { episode: 20, artist: "Queens of the Stone Age", song: "Go With The Flow" },
  { episode: 21, artist: "Stone Temple Pilots", song: "Interstate Love Song" },
  { episode: 22, artist: "System Of A Down", song: "Chop Suey!" },
  { episode: 23, artist: "Red Hot Chili Peppers", song: "Give It Away" },
  { episode: 24, artist: "Peter Gabriel", song: "In Your Eyes" },
  { episode: 25, artist: "David Bowie", song: "Let's Dance" },
  { episode: 26, artist: "Nine Inch Nails", song: "The Hand That Feeds" },
  { episode: 27, artist: "Alanis Morissette", song: "You Oughta Know" },
  { episode: 28, artist: "Coldplay", song: "Clocks" },
  { episode: 29, artist: "The Police", song: "Every Breath You Take" },
  { episode: 30, artist: "Muse", song: "Starlight" },
  { episode: 31, artist: "Steely Dan", song: "Don't Take Me Alive" },
  { episode: 32, artist: "Yes", song: "Roundabout" },
  { episode: 33, artist: "Incubus", song: "Pardon Me" },
  { episode: 34, artist: "Jane's Addiction", song: "Been Caught Stealing" },
  { episode: 35, artist: "Oasis", song: "Wonderwall" },
  { episode: 36, artist: "Adele", song: "Rumor Has It" },
  { episode: 37, artist: "Tool", song: "Parabola" },
  { episode: 38, artist: "Led Zeppelin", song: "Whole Lotta Love" },
  { episode: 39, artist: "Nirvana", song: "Heart-Shaped Box" },
  { episode: 40, artist: "The Chainsmokers ft. Halsey", song: "Closer" },
  { episode: 41, artist: "Periphery", song: "Absolomb" },
  { episode: 42, artist: "Pearl Jam", song: "Garden" },
  { episode: 43, artist: "Tears For Fears", song: "Head Over Heels" },
  { episode: 44, artist: "Mastodon", song: "Stargasm" },
  { episode: 45, artist: "U2", song: "In God's Country" },
  { episode: 46, artist: "Tom Petty", song: "Free Fallin'" },
  { episode: 47, artist: "The Beatles", song: "Her Majesty" },
  { episode: 48, artist: "Green Day", song: "Boulevard Of Broken Dreams" },
  { episode: 49, artist: "Faith No More", song: "Epic" },
  { episode: 50, artist: "Faith No More", song: "Epic" },
  { episode: 51, artist: "Avenged Sevenfold", song: "Shepherd Of Fire" },
  { episode: 52, artist: "Alice In Chains", song: "Man in the Box" },
  { episode: 53, artist: "Genesis", song: "Dance On A Volcano" },
  { episode: 54, artist: "The Doors", song: "Touch Me" },
  { episode: 55, artist: "Weezer", song: "Hash Pipe" },
  { episode: 56, artist: "Van Halen", song: "Panama" },
  { episode: 57, artist: "Deftones", song: "Change (In the House of Flies)" },
  { episode: 58, artist: "R.E.M.", song: "Losing My Religion" },
  { episode: 59, artist: "Rage Against The Machine", song: "Bulls On Parade" },
  { episode: 60, artist: "The Who", song: "Won't Get Fooled Again" },
  { episode: 61, artist: "Radiohead", song: "Karma Police" },
  { episode: 62, artist: "Rush", song: "Limelight" },
  { episode: 63, artist: "Megadeth", song: "Symphony Of Destruction" },
  { episode: 64, artist: "Failure", song: "Stuck On You" },
  { episode: 65, artist: "Journey", song: "Don't Stop Believin'" },
  { episode: 66, artist: "Pantera", song: "Walk" },
  { episode: 67, artist: "Boston", song: "More Than a Feeling" },
  { episode: 68, artist: "Plini", song: "Electric Sunrise" },
  { episode: 69, artist: "The Rolling Stones", song: "Angie" },
  { episode: 70, artist: "Jeff Buckley", song: "Vancouver" },
  { episode: 71, artist: "Red Hot Chili Peppers", song: "Under The Bridge" },
  { episode: 72, artist: "XTC", song: "Mayor Of Simpleton" },
  { episode: 73, artist: "R.E.M.", song: "Losing My Religion" },
  { episode: 74, artist: "Deftones", song: "Minerva" },
  { episode: 75, artist: "Foo Fighters", song: "The Pretender" },
  { episode: 76, artist: "Kansas", song: "Carry on Wayward Son" },
  { episode: 77, artist: "R.E.M.", song: "The One I Love" },
  { episode: 78, artist: "Deftones", song: "My Own Summer (Shove It)" },
  { episode: 79, artist: "The Cure", song: "Just Like Heaven" },
  { episode: 80, artist: "Oasis", song: "Don't Look Back In Anger" },
  { episode: 81, artist: "Third Eye Blind", song: "Semi-Charmed Life" },
  { episode: 82, artist: "Led Zeppelin", song: "Ramble On" },
  { episode: 83, artist: "The White Stripes", song: "Seven Nation Army" },
  { episode: 84, artist: "Karnivool", song: "Goliath" },
  { episode: 85, artist: "Korn", song: "Freak On a Leash" },
  { episode: 86, artist: "Nirvana", song: "Smells Like Teen Spirit" },
  { episode: 87, artist: "Joni Mitchell", song: "Amelia" },
  { episode: 88, artist: "Pearl Jam", song: "Black" },
  { episode: 89, artist: "Coldplay", song: "The Scientist" },
  { episode: 90, artist: "Gordon Lightfoot", song: "If You Could Read My Mind" },
  { episode: 91, artist: "Stevie Wonder", song: "Superstition" },
  { episode: 92, artist: "Elton John", song: "Rocket Man" },
  { episode: 93, artist: "Fleetwood Mac", song: "The Chain" },
  { episode: 94, artist: "Simon & Garfunkel", song: "The Boxer" },
  { episode: 95, artist: "The Cars", song: "Just What I Needed" },
  { episode: 96, artist: "AC/DC", song: "Back in Black" },
  { episode: 97, artist: "Steely Dan", song: "Peg" },
  { episode: 98, artist: "The Eagles", song: "Hotel California" },
  { episode: 99, artist: "Sting", song: "Fields of Gold" },
  { episode: 100, artist: "Radiohead", song: "Paranoid Android" },
  { episode: 101, artist: "Rage Against The Machine", song: "Killing In the Name" },
  { episode: 102, artist: "U2", song: "I Still Haven't Found What I'm Looking For" },
  { episode: 103, artist: "Polyphia", song: "G.O.A.T." },
  { episode: 104, artist: "Seal", song: "Kiss From A Rose" },
  { episode: 105, artist: "Fleetwood Mac", song: "Go Your Own Way" },
  { episode: 106, artist: "Queens of the Stone Age", song: "No One Knows" },
  { episode: 107, artist: "Slipknot", song: "Before I Forget" },
  { episode: 108, artist: "Queen", song: "Bohemian Rhapsody" },
  { episode: 109, artist: "Chicago", song: "Make Me Smile" },
  { episode: 110, artist: "The Police", song: "Murder by Numbers" },
  { episode: 111, artist: "blink-182", song: "What's My Age Again?" },
  { episode: 112, artist: "Bon Jovi", song: "Living on a Prayer" },
  { episode: 113, artist: "Tears for Fears", song: "Everybody Wants to Rule the World" },
  { episode: 114, artist: "Elton John", song: "Tiny Dancer" },
  { episode: 115, artist: "The Killers", song: "Mr. Brightside" }
];
