// Complete list of Rick Beato's "What Makes This Song Great" episodes with genre classifications
const songsData = [
  { episode: 1, artist: "Blink-182", song: "All the Small Things", genres: ["Pop Punk", "Alternative Rock"] },
  { episode: 2, artist: "The Police", song: "Every Little Thing She Does Is Magic", genres: ["New Wave", "Rock", "Pop"] },
  { episode: 3, artist: "Steely Dan", song: "Kid Charlemagne", genres: ["Jazz Fusion", "Rock", "Soft Rock"] },
  { episode: 4, artist: "Nirvana", song: "On A Plain", genres: ["Grunge", "Alternative Rock"] },
  { episode: 5, artist: "Pearl Jam", song: "Jeremy", genres: ["Grunge", "Alternative Rock"] },
  { episode: 6, artist: "Linkin Park", song: "Numb", genres: ["Nu Metal", "Alternative Rock", "Electronic"] },
  { episode: 7, artist: "Tom Petty", song: "I Won't Back Down", genres: ["Rock", "Heartland Rock"] },
  { episode: 8, artist: "A Perfect Circle", song: "Judith", genres: ["Alternative Metal", "Progressive Rock"] },
  { episode: 9, artist: "Toto", song: "Rosanna", genres: ["Rock", "Pop Rock", "Soft Rock"] },
  { episode: 10, artist: "Soundgarden", song: "Superunknown", genres: ["Grunge", "Alternative Metal"] },
  { episode: 11, artist: "Metallica", song: "Enter Sandman", genres: ["Heavy Metal", "Thrash Metal"] },
  { episode: 12, artist: "Alice In Chains", song: "Them Bones", genres: ["Grunge", "Alternative Metal"] },
  { episode: 13, artist: "Tool", song: "Schism", genres: ["Progressive Metal", "Alternative Metal"] },
  { episode: 14, artist: "Foo Fighters", song: "Everlong", genres: ["Alternative Rock", "Post-Grunge"] },
  { episode: 15, artist: "Tool", song: "Schism", genres: ["Progressive Metal", "Alternative Metal"] },
  { episode: 16, artist: "Foo Fighters", song: "Everlong", genres: ["Alternative Rock", "Post-Grunge"] },
  { episode: 17, artist: "Boston", song: "Hitch a Ride", genres: ["Classic Rock", "Hard Rock"] },
  { episode: 18, artist: "Ariana Grande", song: "Into You", genres: ["Pop", "R&B"] },
  { episode: 19, artist: "Rush", song: "Closer to the Heart", genres: ["Progressive Rock", "Hard Rock"] },
  { episode: 20, artist: "Queens of the Stone Age", song: "Go With The Flow", genres: ["Alternative Rock", "Stoner Rock"] },
  { episode: 21, artist: "Stone Temple Pilots", song: "Interstate Love Song", genres: ["Grunge", "Alternative Rock"] },
  { episode: 22, artist: "System Of A Down", song: "Chop Suey!", genres: ["Alternative Metal", "Nu Metal"] },
  { episode: 23, artist: "Red Hot Chili Peppers", song: "Give It Away", genres: ["Funk Rock", "Alternative Rock"] },
  { episode: 24, artist: "Peter Gabriel", song: "In Your Eyes", genres: ["Art Rock", "Pop Rock"] },
  { episode: 25, artist: "David Bowie", song: "Let's Dance", genres: ["Pop Rock", "Dance", "New Wave"] },
  { episode: 26, artist: "Nine Inch Nails", song: "The Hand That Feeds", genres: ["Industrial Rock", "Alternative Rock"] },
  { episode: 27, artist: "Alanis Morissette", song: "You Oughta Know", genres: ["Alternative Rock", "Pop Rock"] },
  { episode: 28, artist: "Coldplay", song: "Clocks", genres: ["Alternative Rock", "Pop Rock"] },
  { episode: 29, artist: "The Police", song: "Every Breath You Take", genres: ["New Wave", "Rock", "Pop"] },
  { episode: 30, artist: "Muse", song: "Starlight", genres: ["Alternative Rock", "Progressive Rock"] },
  { episode: 31, artist: "Steely Dan", song: "Don't Take Me Alive", genres: ["Jazz Fusion", "Rock", "Soft Rock"] },
  { episode: 32, artist: "Yes", song: "Roundabout", genres: ["Progressive Rock", "Art Rock"] },
  { episode: 33, artist: "Incubus", song: "Pardon Me", genres: ["Alternative Rock", "Funk Metal"] },
  { episode: 34, artist: "Jane's Addiction", song: "Been Caught Stealing", genres: ["Alternative Rock", "Funk Rock"] },
  { episode: 35, artist: "Oasis", song: "Wonderwall", genres: ["Britpop", "Alternative Rock"] },
  { episode: 36, artist: "Adele", song: "Rumor Has It", genres: ["Pop", "Soul"] },
  { episode: 37, artist: "Tool", song: "Parabola", genres: ["Progressive Metal", "Alternative Metal"] },
  { episode: 38, artist: "Led Zeppelin", song: "Whole Lotta Love", genres: ["Hard Rock", "Blues Rock", "Classic Rock"] },
  { episode: 39, artist: "Nirvana", song: "Heart-Shaped Box", genres: ["Grunge", "Alternative Rock"] },
  { episode: 40, artist: "The Chainsmokers ft. Halsey", song: "Closer", genres: ["Electronic", "Pop", "EDM"] },
  { episode: 41, artist: "Periphery", song: "Absolomb", genres: ["Progressive Metal", "Djent"] },
  { episode: 42, artist: "Pearl Jam", song: "Garden", genres: ["Grunge", "Alternative Rock"] },
  { episode: 43, artist: "Tears For Fears", song: "Head Over Heels", genres: ["New Wave", "Synth-pop"] },
  { episode: 44, artist: "Mastodon", song: "Stargasm", genres: ["Progressive Metal", "Sludge Metal"] },
  { episode: 45, artist: "U2", song: "In God's Country", genres: ["Rock", "Alternative Rock"] },
  { episode: 46, artist: "Tom Petty", song: "Free Fallin'", genres: ["Rock", "Heartland Rock"] },
  { episode: 47, artist: "The Beatles", song: "Her Majesty", genres: ["Rock", "Pop"] },
  { episode: 48, artist: "Green Day", song: "Boulevard Of Broken Dreams", genres: ["Pop Punk", "Alternative Rock"] },
  { episode: 49, artist: "Faith No More", song: "Epic", genres: ["Alternative Metal", "Funk Metal"] },
  { episode: 50, artist: "Faith No More", song: "Epic", genres: ["Alternative Metal", "Funk Metal"] },
  { episode: 51, artist: "Avenged Sevenfold", song: "Shepherd Of Fire", genres: ["Heavy Metal", "Hard Rock"] },
  { episode: 52, artist: "Alice In Chains", song: "Man in the Box", genres: ["Grunge", "Alternative Metal"] },
  { episode: 53, artist: "Genesis", song: "Dance On A Volcano", genres: ["Progressive Rock", "Art Rock"] },
  { episode: 54, artist: "The Doors", song: "Touch Me", genres: ["Psychedelic Rock", "Classic Rock"] },
  { episode: 55, artist: "Weezer", song: "Hash Pipe", genres: ["Alternative Rock", "Power Pop"] },
  { episode: 56, artist: "Van Halen", song: "Panama", genres: ["Hard Rock", "Classic Rock"] },
  { episode: 57, artist: "Deftones", song: "Change (In the House of Flies)", genres: ["Alternative Metal", "Nu Metal"] },
  { episode: 58, artist: "R.E.M.", song: "Losing My Religion", genres: ["Alternative Rock", "Jangle Pop"] },
  { episode: 59, artist: "Rage Against The Machine", song: "Bulls On Parade", genres: ["Rap Metal", "Alternative Metal"] },
  { episode: 60, artist: "The Who", song: "Won't Get Fooled Again", genres: ["Hard Rock", "Classic Rock"] },
  { episode: 61, artist: "Radiohead", song: "Karma Police", genres: ["Alternative Rock", "Art Rock"] },
  { episode: 62, artist: "Rush", song: "Limelight", genres: ["Progressive Rock", "Hard Rock"] },
  { episode: 63, artist: "Megadeth", song: "Symphony Of Destruction", genres: ["Thrash Metal", "Heavy Metal"] },
  { episode: 64, artist: "Failure", song: "Stuck On You", genres: ["Alternative Rock", "Space Rock"] },
  { episode: 65, artist: "Journey", song: "Don't Stop Believin'", genres: ["Rock", "Arena Rock"] },
  { episode: 66, artist: "Pantera", song: "Walk", genres: ["Groove Metal", "Heavy Metal"] },
  { episode: 67, artist: "Boston", song: "More Than a Feeling", genres: ["Classic Rock", "Hard Rock"] },
  { episode: 68, artist: "Plini", song: "Electric Sunrise", genres: ["Progressive Metal", "Instrumental Rock"] },
  { episode: 69, artist: "The Rolling Stones", song: "Angie", genres: ["Rock", "Classic Rock"] },
  { episode: 70, artist: "Jeff Buckley", song: "Vancouver", genres: ["Alternative Rock", "Singer-Songwriter"] },
  { episode: 71, artist: "Red Hot Chili Peppers", song: "Under The Bridge", genres: ["Funk Rock", "Alternative Rock"] },
  { episode: 72, artist: "XTC", song: "Mayor Of Simpleton", genres: ["New Wave", "Pop Rock"] },
  { episode: 73, artist: "R.E.M.", song: "Losing My Religion", genres: ["Alternative Rock", "Jangle Pop"] },
  { episode: 74, artist: "Deftones", song: "Minerva", genres: ["Alternative Metal", "Nu Metal"] },
  { episode: 75, artist: "Foo Fighters", song: "The Pretender", genres: ["Alternative Rock", "Post-Grunge"] },
  { episode: 76, artist: "Kansas", song: "Carry on Wayward Son", genres: ["Progressive Rock", "Classic Rock"] },
  { episode: 77, artist: "R.E.M.", song: "The One I Love", genres: ["Alternative Rock", "Jangle Pop"] },
  { episode: 78, artist: "Deftones", song: "My Own Summer (Shove It)", genres: ["Alternative Metal", "Nu Metal"] },
  { episode: 79, artist: "The Cure", song: "Just Like Heaven", genres: ["Alternative Rock", "New Wave"] },
  { episode: 80, artist: "Oasis", song: "Don't Look Back In Anger", genres: ["Britpop", "Alternative Rock"] },
  { episode: 81, artist: "Third Eye Blind", song: "Semi-Charmed Life", genres: ["Alternative Rock", "Pop Rock"] },
  { episode: 82, artist: "Led Zeppelin", song: "Ramble On", genres: ["Hard Rock", "Folk Rock", "Classic Rock"] },
  { episode: 83, artist: "The White Stripes", song: "Seven Nation Army", genres: ["Garage Rock", "Alternative Rock"] },
  { episode: 84, artist: "Karnivool", song: "Goliath", genres: ["Progressive Rock", "Alternative Rock"] },
  { episode: 85, artist: "Korn", song: "Freak On a Leash", genres: ["Nu Metal", "Alternative Metal"] },
  { episode: 86, artist: "Nirvana", song: "Smells Like Teen Spirit", genres: ["Grunge", "Alternative Rock"] },
  { episode: 87, artist: "Joni Mitchell", song: "Amelia", genres: ["Folk Rock", "Singer-Songwriter"] },
  { episode: 88, artist: "Pearl Jam", song: "Black", genres: ["Grunge", "Alternative Rock"] },
  { episode: 89, artist: "Coldplay", song: "The Scientist", genres: ["Alternative Rock", "Pop Rock"] },
  { episode: 90, artist: "Gordon Lightfoot", song: "If You Could Read My Mind", genres: ["Folk", "Singer-Songwriter"] },
  { episode: 91, artist: "Stevie Wonder", song: "Superstition", genres: ["Funk", "Soul", "R&B"] },
  { episode: 92, artist: "Elton John", song: "Rocket Man", genres: ["Pop Rock", "Soft Rock"] },
  { episode: 93, artist: "Fleetwood Mac", song: "The Chain", genres: ["Rock", "Soft Rock"] },
  { episode: 94, artist: "Simon & Garfunkel", song: "The Boxer", genres: ["Folk Rock", "Singer-Songwriter"] },
  { episode: 95, artist: "The Cars", song: "Just What I Needed", genres: ["New Wave", "Power Pop"] },
  { episode: 96, artist: "AC/DC", song: "Back in Black", genres: ["Hard Rock", "Classic Rock"] },
  { episode: 97, artist: "Steely Dan", song: "Peg", genres: ["Jazz Fusion", "Rock", "Soft Rock"] },
  { episode: 98, artist: "The Eagles", song: "Hotel California", genres: ["Rock", "Classic Rock"] },
  { episode: 99, artist: "Sting", song: "Fields of Gold", genres: ["Pop Rock", "Soft Rock"] },
  { episode: 100, artist: "Radiohead", song: "Paranoid Android", genres: ["Alternative Rock", "Art Rock", "Progressive Rock"] },
  { episode: 101, artist: "Rage Against The Machine", song: "Killing In the Name", genres: ["Rap Metal", "Alternative Metal"] },
  { episode: 102, artist: "U2", song: "I Still Haven't Found What I'm Looking For", genres: ["Rock", "Alternative Rock"] },
  { episode: 103, artist: "Polyphia", song: "G.O.A.T.", genres: ["Progressive Rock", "Instrumental Rock"] },
  { episode: 104, artist: "Seal", song: "Kiss From A Rose", genres: ["Pop", "Soul"] },
  { episode: 105, artist: "Fleetwood Mac", song: "Go Your Own Way", genres: ["Rock", "Soft Rock"] },
  { episode: 106, artist: "Queens of the Stone Age", song: "No One Knows", genres: ["Alternative Rock", "Stoner Rock"] },
  { episode: 107, artist: "Slipknot", song: "Before I Forget", genres: ["Nu Metal", "Heavy Metal"] },
  { episode: 108, artist: "Queen", song: "Bohemian Rhapsody", genres: ["Progressive Rock", "Opera Rock", "Classic Rock"] },
  { episode: 109, artist: "Chicago", song: "Make Me Smile", genres: ["Jazz Rock", "Rock"] },
  { episode: 110, artist: "The Police", song: "Murder by Numbers", genres: ["New Wave", "Rock"] },
  { episode: 111, artist: "blink-182", song: "What's My Age Again?", genres: ["Pop Punk", "Alternative Rock"] },
  { episode: 112, artist: "Bon Jovi", song: "Living on a Prayer", genres: ["Hard Rock", "Glam Metal"] },
  { episode: 113, artist: "Tears for Fears", song: "Everybody Wants to Rule the World", genres: ["New Wave", "Synth-pop"] },
  { episode: 114, artist: "Elton John", song: "Tiny Dancer", genres: ["Pop Rock", "Soft Rock"] },
  { episode: 115, artist: "The Killers", song: "Mr. Brightside", genres: ["Alternative Rock", "Indie Rock"] }
];

// Extract all unique genres for filtering
const allGenres = [...new Set(songsData.flatMap(song => song.genres))].sort();
